import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const NOTIFY_URL = Deno.env.get('SUPABASE_URL') + '/functions/v1/send-notification'
const NOTIFY_KEY = Deno.env.get('SUPABASE_ANON_KEY')

serve(async () => {
    const supabase = createClient(
            Deno.env.get('SUPABASE_URL'),
                    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
                        )

                            const today = new Date().toISOString().split('T')[0]

                                // Fetch all active investments — include user info for the notification
                                    const { data: investments, error } = await supabase
                                            .from('transactions')
                                                    .select('id, user_id, amount, daily_rate, end_date, duration_days, method, reference, users(full_name, first_name, email)')
                                                            .eq('type', 'investment')
                                                                    .eq('status', 'completed')
                                                                            .eq('inv_active', true)

                                                                                if (error) {
                                                                                        console.error('Fetch error:', error.message)
                                                                                                return new Response(JSON.stringify({ error: error.message }), { status: 500 })
                                                                                                    }

                                                                                                        let credited  = 0
                                                                                                            let completed = 0

                                                                                                                for (const inv of investments || []) {
                                                                                                                        const dailyEarn = parseFloat(inv.amount) * (parseFloat(inv.daily_rate) / 100)

                                                                                                                                if (inv.end_date <= today) {
                                                                                                                                            // Investment matured — return principal + total profit to balance
                                                                                                                                                        // BUG FIX: was `< today` which would skip notifications on the exact end date
                                                                                                                                                                    const totalProfit = parseFloat(inv.amount) * (parseFloat(inv.daily_rate) / 100) * (inv.duration_days || 30)

                                                                                                                                                                                const { error: rpcError } = await supabase.rpc('complete_investment', {
                                                                                                                                                                                                p_user_id: inv.user_id,
                                                                                                                                                                                                                p_amount:  parseFloat(inv.amount),
                                                                                                                                                                                                                                p_profit:  totalProfit,
                                                                                                                                                                                                                                                p_tx_id:   inv.id,
                                                                                                                                                                                                                                                            })

                                                                                                                                                                                                                                                                        if (rpcError) {
                                                                                                                                                                                                                                                                                        console.error(`complete_investment failed for tx ${inv.id}:`, rpcError.message)
                                                                                                                                                                                                                                                                                                        continue  // don't notify if the RPC failed
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                completed++

                                                                                                                                                                                                                                                                                                                                            // Send maturity notification — only after RPC succeeds
                                                                                                                                                                                                                                                                                                                                                        const userName  = inv.users?.full_name || inv.users?.first_name || 'Valued Investor'
                                                                                                                                                                                                                                                                                                                                                                    const userEmail = inv.users?.email || ''

                                                                                                                                                                                                                                                                                                                                                                                if (userEmail) {
                                                                                                                                                                                                                                                                                                                                                                                                await fetch(NOTIFY_URL, {
                                                                                                                                                                                                                                                                                                                                                                                                                    method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Content-Type':  'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'apikey':        NOTIFY_KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Authorization': `Bearer ${NOTIFY_KEY}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type:   'investment_matured',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        email:  userEmail,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name:   userName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        amount: `$${parseFloat(inv.amount).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                plan:   inv.method || 'Investment Plan',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ref:    inv.reference || inv.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Still active — credit today's daily earnings to profit column
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .from('users')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .update({ profit: supabase.raw(`profit + ${dailyEarn}`) })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .eq('id', inv.user_id)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    credited++
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            JSON.stringify({ success: true, credited, completed }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { headers: { 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })